"""
PUTKI HQ - Profiler routes (iter66 modularisation phase 1).

Extracted from server.py to start chipping away at the 4750-LOC monolith.
This module owns the 4 newest endpoints (iter64-iter65 era):

    POST /api/profiler/event              - funnel beacon
    GET  /api/admin/profiler/funnel       - back-office dashboard data
    GET  /api/profiler/share/og.png       - autogenerated PNG identity card
    GET  /api/profiler/share/u/{key}      - SSR unfurl landing page

The `build_profiler_router(db, require_admin)` factory takes the live
Mongo handle + admin dependency from server.py and returns a configured
APIRouter that gets mounted into the app. Tests don't break - route
paths are unchanged.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel

import profiler_funnel as _pf
import profiler_og as _og


class ProfilerEventPayload(BaseModel):
    session_id: str
    event: str
    meta: Optional[Dict[str, Any]] = None


def build_profiler_router(db, require_admin) -> APIRouter:
    """Returns an APIRouter mounted under /api by the caller. `db` is the
    live AsyncIOMotorClient database handle; `require_admin` is the
    FastAPI dependency that gates admin-scoped routes."""
    router = APIRouter()

    @router.post("/profiler/event")
    async def profiler_event(payload: ProfilerEventPayload):
        """Fire-and-forget funnel beacon. Frontend posts at each funnel step
        (session_start → session_complete → reveal_view → gate_view →
        gate_submit_attempt → gate_unlocked → share_click / tg_click).
        All events live in `profiler_events` with a 30-day TTL."""
        result = await _pf.record_event(
            db, event=payload.event, session_id=payload.session_id,
            meta=payload.meta or {},
        )
        if result.get("error"):
            raise HTTPException(400, result["error"])
        return result

    @router.get("/admin/profiler/funnel")
    async def admin_profiler_funnel(since_days: int = 7, _: bool = Depends(require_admin)):
        """Back-office funnel dashboard widget data - aggregate counts +
        step-to-step conversion rates over the trailing `since_days`."""
        return await _pf.funnel_summary(db, since_days=since_days)

    @router.get("/profiler/share/og.png")
    async def profiler_share_og(persona_key: Optional[str] = None,
                                play_id: Optional[str] = None,
                                lang: str = "fi"):
        """Return a 1200×630 PNG identity card suitable for Twitter/Telegram/
        Discord unfurl previews. Either `persona_key` or `play_id` works -
        `play_id` looks up the stored persona automatically."""
        chosen_key = persona_key
        if not chosen_key and play_id:
            play = await db.mini_game_plays.find_one(
                {"play_id": play_id}, {"_id": 0, "persona_key": 1, "persona": 1},
            )
            if play:
                chosen_key = (play.get("persona") or {}).get("key") or play.get("persona_key")
        if not chosen_key:
            chosen_key = "patient_tactician"  # honest neutral fallback
        png = _og.render_from_persona_key(chosen_key, lang=lang if lang in ("fi", "en") else "fi")
        return Response(
            content=png,
            media_type="image/png",
            headers={
                "Cache-Control": "public, max-age=86400, immutable",
                "Content-Disposition": 'inline; filename="putki-profile.png"',
            },
        )

    return router


def build_profiler_share_landing_html(persona_key: str, lang: str = "fi") -> str:
    """Pure helper extracted for unit-testability - composes the SSR
    unfurl HTML. The endpoint is wired in `register_share_landing()`
    below since it sits on the bare `app` (no /api prefix on the path)."""
    fi_name, en_name, idx = _og.PROFILE_DISPLAY.get(
        persona_key, ("Pelaajaprofiili", "Your Player Profile", "01 / 05"),
    )
    display = en_name if lang == "en" else fi_name
    if lang == "en":
        title = f"I'm {display} - what are you?"
        desc  = (f"PUTKI HQ behavioral profiler · {idx}. "
                 "Six honest decisions. No trivia. Take it free.")
    else:
        title = f"Olen {display} - mikä sinä olet?"
        desc  = (f"PUTKI HQ pelaajaprofiili · {idx}. "
                 "Kuusi rehellistä päätöstä. Ei tietovisaa. Tee se ilmaiseksi.")
    og_image = f"/api/profiler/share/og.png?persona_key={persona_key}&lang={lang}"
    redirect_to = f"/peliareena?profile={persona_key}"

    return f"""<!doctype html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta property="og:type"        content="website">
<meta property="og:title"       content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image"       content="{og_image}">
<meta property="og:image:width"  content="1200">
<meta property="og:image:height" content="630">
<meta property="og:url"         content="https://putkihq.fi{redirect_to}">
<meta property="og:site_name"   content="PUTKI HQ">
<meta name="twitter:card"        content="summary_large_image">
<meta name="twitter:title"       content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image"       content="{og_image}">
<meta http-equiv="refresh" content="0; url={redirect_to}">
<style>
  body {{ font-family: Georgia, serif; background: #fbfaf8; color: #1c1a18;
          margin: 0; padding: 60px 24px; text-align: center; }}
  h1 {{ font-size: 28px; margin: 0 0 12px; }}
  p  {{ color: #6b665f; font-size: 16px; }}
  a  {{ color: #b07d18; }}
</style>
</head>
<body>
  <h1>{title}</h1>
  <p>{desc}</p>
  <p><a href="{redirect_to}">→ {("Continue" if lang == "en" else "Jatka")}</a></p>
</body>
</html>"""


def register_share_landing(app) -> None:
    """The unfurl landing sits on the bare `app` (not the /api router)
    because the full path `/api/profiler/share/u/{key}` is treated as
    a synchronous public asset by ingress. Wired here for parity with
    the rest of the profiler routes."""

    @app.get("/api/profiler/share/u/{persona_key}", response_class=Response)
    async def profiler_share_landing(persona_key: str, lang: str = "fi"):
        """Server-rendered share landing page with og:image meta tags.
        Social crawlers (Twitterbot, Slackbot, Telegrambot, Discordbot,
        etc.) fetch this URL when a user shares the link - they read
        the meta tags and render the unfurl card. Real human visitors
        get auto-redirected to /peliareena via a meta-refresh."""
        html = build_profiler_share_landing_html(persona_key, lang=lang)
        return Response(content=html, media_type="text/html; charset=utf-8")
