/**
 * LegalDisclaimer - permanent UI element on every Article page (per launch
 * spec). NOT generated by the LLM. Elegant callout box at the bottom of the
 * article body, before the tag pills.
 */
import React from 'react';
import { AlertTriangle } from 'lucide-react';

const LegalDisclaimer = () => (
  <aside
    data-testid="legal-disclaimer"
    className="mt-10 flex gap-3"
    style={{
      padding: '16px 18px',
      background: 'rgba(44, 95, 141, 0.05)',
      border: '1px solid rgba(44, 95, 141, 0.22)',
      borderLeft: '3px solid #2C5F8D',
      borderRadius: 2,
    }}
  >
    <AlertTriangle
      size={16}
      strokeWidth={1.8}
      style={{ flexShrink: 0, marginTop: 2, color: '#2C5F8D' }}
    />
    <p
      className="font-serif"
      style={{ fontSize: 13, lineHeight: 1.55, color: 'var(--muted)', margin: 0 }}
    >
      Sisältömme perustuu asiantuntijoidemme mielipiteisiin eikä ole vedonlyöntisuosituksia.
      Vedonlyönti on aina riskialtista - pelaa vastuullisesti.
    </p>
  </aside>
);

export default LegalDisclaimer;
